In [2]:
import numpy as np

In [2]:
a=np.array(np.random.randint(100, size=(2, 15)))
np.any(a>50, axis=0)

array([ True,  True,  True,  True,  True, False,  True, False, False,
        True,  True, False,  True,  True,  True])

In [3]:
((a>20) & (a<60))

array([[ True, False, False,  True,  True, False, False,  True,  True,
        False, False,  True,  True,  True, False],
       [ True,  True, False, False, False,  True, False,  True, False,
        False, False,  True, False, False,  True]])

In [4]:
array = np.arange(1000)
array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [5]:
array[[1,5,78]]

array([ 1,  5, 78])

In [6]:
print(array.size * array.itemsize)  # or simply array.nbytes

8000


In [7]:
# if two np arrays of any equal dimensions are there, a1 and a2
# then a1<arithmetic_operator>a2 will return numpy array where corresponding array elements are processed

In [8]:
a=np.array([1, 2, 3])
a.ndim

1

In [9]:
a.dtype

dtype('int64')

In [10]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
a.ndim

2

In [11]:
a.size

9

In [12]:
a.itemsize

8

In [13]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.float64)
print(a.dtype)
print(a.itemsize)
a

float64
8


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
a.shape

(3, 3)

In [15]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [16]:
a=np.zeros( (3, 4) )    # if 1d array is there, np.zeros(length of 1 d array)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
a = np.ones( (2, 5) , dtype=np.int8)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [18]:
# generic
np.full( (2,2), 99 )

array([[99, 99],
       [99, 99]])

In [19]:
np.full_like(a, 78) # returns new array of shape of a, with 78

array([[78, 78, 78, 78, 78],
       [78, 78, 78, 78, 78]], dtype=int8)

In [20]:
np.full(a.shape, 56)    # a wont get changed

array([[56, 56, 56, 56, 56],
       [56, 56, 56, 56, 56]])

In [21]:
np.arange(1,5)

array([1, 2, 3, 4])

In [22]:
np.arange(1,5,2)

array([1, 3])

In [23]:
np.linspace(1, 5, 10)   # linearly spaced 10 numbers between 1 and 5 both included

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
a = np.array([[1,2,3], [4,5,6]])
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = a.ravel()   # to flatten the array
a

array([1, 2, 3, 4, 5, 6])

In [26]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [27]:
a.flat  # gives flatter iterable object, NOT numpy array

In [28]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.min(), a.max(), a.sum(axis=1) )

1 9 [ 6 15 24]


In [29]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
np.std(a)

2.581988897471611

In [31]:
b=np.array([[1,1,1], [1,1,1], [1,1,1]]) # matrix product
print(a)
print(b)
np.dot(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [32]:
# stacking two arrays together
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a, b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]] [[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [33]:
a=np.array([np.arange(15), np.arange(15,30)])
print(a)
print(np.hsplit(a,3))
# similar goes with vsplit. Remember, the dimension of array will NOT gets reduced in both the cases

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [34]:
# np array indexing with boolean array
a=np.arange(12).reshape(3,4)
b = a > 4
print(b)
print(a[b]) # or directly a[a>4]
a[b]=-1
print(a)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [35]:
# np.nditer() function
a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='C'):
    print(x)

for x in np.nditer(a, order='F'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
0
4
8
1
5
9
2
6
10
3
7
11


In [36]:
# printing 1D array instead of 0D array
a = np.arange(12).reshape(3,4)
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [37]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [38]:
b=np.arange(3, 15,4).reshape(3, 1)
print(b)
for x,y in np.nditer([a,b], order='C'): # this will work only if dimensions are equal or if one of the array dimension is 1
    print(x,y)

[[ 3]
 [ 7]
 [11]]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [3]:
np.random.rand(4,2)

array([[0.52292134, 0.69565466],
       [0.00193356, 0.54718732],
       [0.8464286 , 0.55433283],
       [0.36729023, 0.95013277]])

In [ ]:
np.random.random((3,4))

array([[0.30807692, 0.75138772, 0.15415681, 0.37504647],
       [0.19305003, 0.50323679, 0.34808706, 0.0227335 ],
       [0.23647292, 0.03279351, 0.07502302, 0.47892285]])

In [ ]:
np.random.random_sample(a.shape)*10

array([[5.0336057 , 5.41752604, 2.31560543, 5.40908844],
       [7.68975085, 1.84081094, 0.60208532, 5.71891441],
       [8.73036322, 9.46287681, 1.50549888, 7.60752859]])

In [ ]:
np.random.random(a.shape)*10

array([[4.00073184, 4.11928202, 5.47200706, 8.66587192],
       [1.23179535, 4.62862452, 7.93197618, 8.42399414],
       [3.50087886, 8.56618802, 1.66566512, 8.80438538]])

In [ ]:
np.random.randint(8, size=(4,5))    # ([start(inc)(0 by default, can allso be -ve),] end(exl) [,size=(r,c)])

array([[7, 3, 6, 3, 5],
       [7, 1, 7, 6, 3],
       [0, 4, 7, 5, 5],
       [5, 7, 4, 1, 7]])

In [ ]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
# axis param only possible when array is at least 2D or above. Still it is optional. If axis param is not given in any dimensional array, then 1D array is returned where each elemet is repreated n times.
a= np.array([[1,2,3]])
np.repeat(a, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
a= np.array([[1,2,3], [4,5,6]])
np.repeat(a,3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
a[1:-1, 1:-1] = z
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

https://docs.scipy.org/doc/numpy/reference/routines.math.html

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
np.max(stats, axis=0)

array([4, 5, 6])

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.std(stats)

1.707825127659933

In [ ]:
np.std(stats, axis=0)

array([1.5, 1.5, 1.5])

In [ ]:
np.var(stats)

2.9166666666666665

In [ ]:
np.var(stats, axis=1)

array([0.66666667, 0.66666667])

In [ ]:
np.sum(stats)

21

In [ ]:
np.sum(stats, axis=1)

array([ 6, 15])

In [ ]:
np.conjugate(stats)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(stats)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Load data from a file

In [ ]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
a[0:4,1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [ ]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
np.genfromtxt('./sosurveydataset/numdata.csv', delimiter=',').astype('int16')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)