In [2]:
import numpy as np

In [ ]:
np.random.rand()    # uniform dist. [0,1)

0.28223343511696397

In [ ]:
np.random.randn()   # normal dist. [0,1)

0.09215787153869413

In [ ]:
a=np.random.randint(100, size=(2, 15))    # literally, instead of size, there should be shape. BUT HERE IT IS SIZE. We can aslo give the lower limit(inclusive) and upper limit(exclusive), and size of any shape

print(type(a), a)
np.any(a>50, axis=0)

<class 'numpy.ndarray'>
[[13 44 98 58 98 68 12 16 67 23 45 90 95 44 63]
 [61 23 13 41 60  2 20 57 46 80 54 80 70 50 41]]


array([ True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True])

In [28]:
((a>20) & (a<60))

array([[False,  True, False,  True, False, False, False, False, False,
         True,  True, False, False,  True, False],
       [False,  True, False,  True, False, False, False,  True,  True,
        False,  True, False, False,  True,  True]])

In [29]:
np.random.choice([2,3,4,5,6,7,8], size=(3, 5))

array([[8, 5, 6, 2, 3],
       [7, 3, 7, 8, 3],
       [8, 3, 8, 6, 4]])

In [ ]:
np.random.choice([2,3,4,5], p=[0.1, 0.3, 0.6, 0.0], size=(100,))    # we can specify the probablities of random variable/choices also

array([4, 4, 4, 3, 4, 4, 2, 4, 2, 4, 4, 4, 3, 2, 3, 4, 4, 3, 3, 4, 3, 4,
       2, 3, 2, 3, 4, 4, 3, 4, 3, 4, 4, 3, 4, 4, 4, 3, 4, 3, 4, 3, 4, 4,
       3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 3, 4, 3, 4, 4, 3, 4, 4, 2,
       3, 3, 2, 2, 4, 3, 4, 3, 4, 4, 4, 3, 2, 3, 3, 3, 3, 4, 4, 4, 3, 4,
       2, 3, 4, 3, 4, 4, 4, 3, 3, 4, 4, 3])

In [ ]:
b = np.array([1, 2, 3, 4, 5])
np.random.shuffle(b)    # or, permutation()
b   # shuffles the array inplace. In multi-dimension array, all the elements are shuffeled.

array([4, 2, 5, 3, 1])

In [37]:
# seed makes the random numbers predictable. That is, everytime, for the same code, same random output will be generated.
# np.random.seed()    # seed(int_val)

In [15]:
array = np.arange(1000)
array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [16]:
array[[1,5,78]]

array([ 1,  5, 78])

In [17]:
print(array.size * array.itemsize)  # or simply array.nbytes

8000


In [18]:
# if two np arrays of any equal dimensions are there, a1 and a2
# then a1<arithmetic_operator>a2 will return numpy array where corresponding array elements are processed

In [19]:
a=np.array([1, 2, 3])
a.ndim

1

In [ ]:
a.dtype

In [2]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], ndmin=6)
a.ndim

6

In [3]:
a

array([[[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]]])

In [ ]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
a.ndim

In [ ]:
a.size

In [ ]:
a.itemsize

In [ ]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.float64)
print(a.dtype)
print(a.itemsize)
a

In [ ]:
a.shape

In [ ]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=complex)
a

In [ ]:
a=np.zeros( (3, 4) )    # if 1d array is there, np.zeros(length of 1 d array)
a

In [ ]:
a = np.ones( (2, 5) , dtype=np.int8)
a

In [ ]:
# generic
np.full( (2,2), 99 )

In [ ]:
np.full_like(a, 78) # returns new array of shape of a, with 78

In [ ]:
np.full(a.shape, 56)    # a wont get changed

In [ ]:
np.arange(1,5)

In [ ]:
np.arange(1,5,2)

In [ ]:
np.linspace(1, 5, 10)   # linearly spaced 10 numbers between 1 and 5 both included

In [4]:
a = np.array([[1,2,3], [4,5,6]])
a = a.reshape(3,2)  # this returns a new VIEW of BASE array a; a is not changed unless we assign it back to
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(a.reshape(-1, 3))   # -1 means whatever is required to make it 3 columns
print(a.reshape(-1, 5))  # error as 5 columns not possible with 6 elements

[[1 2 3]
 [4 5 6]]


ValueError: cannot reshape array of size 6 into shape (5)

In [ ]:
a = a.ravel()   # to flatten the array. Not fixed to give copy or view of original array
a

In [ ]:
a.flatten() # gives a copy of flattened array

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.reshape(-1) # gives a view of flattened array

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.flat  # gives flatter iterable object, NOT numpy array

In [ ]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.min(), a.max(), a.sum(axis=1) )

In [ ]:
np.sqrt(a)

In [ ]:
np.std(a)

In [ ]:
b=np.array([[1,1,1], [1,1,1], [1,1,1]]) # matrix product
print(a)
print(b)
np.dot(a,b)

In [ ]:
# stacking two arrays together
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a, b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

In [ ]:
a=np.array([np.arange(15), np.arange(15,30)])
print(a)
print(np.hsplit(a,3))
# similar goes with vsplit. Remember, the dimension of array will NOT gets reduced in both the cases

In [ ]:
# np array indexing with boolean array
a=np.arange(12).reshape(3,4)
b = a > 4   # boolean array of dimension of 'a'. Another way to get just the indexes of True, is to use arr.where(conditional_expr) which return an array of indexes of elements, each array contains indx of specific 1-dim from n-dimensions, which holds true.
print(b)
print(a[b]) # or directly a[a>4]
a[b]=-1
print(a)

In [ ]:
# there are many other search and sort ways:
# np.sort(arr)

Object `np.search(arr)` not found.


In [ ]:
# np.nditer() function
a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='C'):
    print(x)

for x in np.nditer(a, order='F'):
    print(x)

In [ ]:
# printing 1D array instead of 0D array
a = np.arange(12).reshape(3,4)
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

In [ ]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x
a

In [ ]:
b=np.arange(3, 15,4).reshape(3, 1)
print(b)
for x,y in np.nditer([a,b], order='C'): # this will work only if dimensions are equal or if one of the array dimension is 1
    print(x,y)

In [ ]:
for idx, ele in np.ndenumerate(a):  # iterates and gives index as well
    print(idx, ele)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6


In [ ]:
np.random.rand(4,2)

In [ ]:
np.random.random((3,4))

In [ ]:
np.random.random_sample(a.shape)*10

In [ ]:
np.random.random(a.shape)*10

In [ ]:
a= np.array([1,2,3])
a

In [ ]:
# axis param only possible when array is at least 2D or above. Still it is optional. If axis param is not given in any dimensional array, then 1D array is returned where each elemet is repreated n times.
a= np.array([[1,2,3]])
np.repeat(a, 3, axis=0)

In [ ]:
a= np.array([[1,2,3], [4,5,6]])
np.repeat(a,3, axis=0)

In [ ]:
np.identity(3)

In [ ]:
a = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
a[1:-1, 1:-1] = z
a

### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)  # or, a @ b

In [ ]:
c = np.identity(3)
np.linalg.det(c)

https://docs.scipy.org/doc/numpy/reference/routines.math.html

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.min(stats, axis=0)

In [ ]:
np.min(stats, axis=1)

In [ ]:
np.max(stats)

In [ ]:
np.max(stats, axis=0)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.std(stats)

In [ ]:
np.std(stats, axis=0)

In [ ]:
np.var(stats)

In [ ]:
np.var(stats, axis=1)

In [ ]:
np.sum(stats)

In [ ]:
np.sum(stats, axis=1)

In [ ]:
np.conjugate(stats)

In [ ]:
np.transpose(stats) # or, stats.T

### Load data from a file

In [ ]:
a = np.arange(1,31).reshape(6,5)
a

In [ ]:
a[[0,1,2,3],[1,2,3,4]]

In [ ]:
a[0:4,1:5]

In [ ]:
a[[0,4,5], 3:]

i - integer;
b - boolean;
u - unsigned integer;
f - float;
c - complex float;
m - timedelta;
M - datetime;
O - object;
S - string;
U - unicode string;
V - fixed chunk of memory for other type ( void );

In [ ]:
np.genfromtxt('./sosurveydataset/numdata.csv', delimiter=',').astype('int16')   # OR 'i16'.  From higher byte to lower byte, data is simply lost, not get rounded off

In [3]:
np.array_split(np.arange(9), 4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [ ]:
# arr.view() V/S arr.copy() 
# Former BASED ON the original array, later creates a new array without reference to the original array arr as BASE.
# any change to original arr or viewed arr will be reflected in both the arrays. But copy is independent.
# to check if an array is view or copy, use arr.base. If it is None, then it is copy, else view.
# ARR.BASE - Its not a method, its an attribute which returns the base array if the array is a view, else returns None.

## DISTRIBUTIONS

In [39]:
np.random.normal(loc=1, scale=2, size=(100,200))  # mean, stddev, size

array([[ 2.49389047,  3.51725024,  1.09980855, ...,  4.95683843,
         1.93553859, -1.89401499],
       [-2.54745337,  0.87076866,  2.6681666 , ...,  2.7208671 ,
        -0.19218676, -0.11024459],
       [ 2.00418966,  2.06752344, -0.9393487 , ...,  0.95962063,
         1.9232324 , -0.27271985],
       ...,
       [ 1.45563668, -3.03292384,  4.08623105, ..., -3.27538772,
        -1.03302648, -0.56319783],
       [-0.55033005,  0.40244865,  1.07706813, ...,  0.22703985,
         2.24537847,  2.95718816],
       [ 1.35405437, -1.4860759 , -0.0422178 , ...,  1.0820936 ,
         2.99885176, -0.38459528]], shape=(100, 200))

In [40]:
np.random.binomial(n=10, p=0.5, size=10)   # n=number of trials, p=probability of each trial, size=number of such experiments

array([6, 8, 6, 5, 5, 0, 4, 6, 2, 5])

In [41]:
np.random.uniform(low=1.0, high=10.0, size=(3,4))   # low(inclusive), high(exclusive), size

array([[1.93609295, 7.60762211, 2.97864083, 5.77176287],
       [6.00787605, 4.92522972, 3.06067745, 3.93895591],
       [4.96577317, 6.52255986, 2.94870296, 6.52459176]])

In [42]:
np.random.poisson(lam=2, size=1000)

array([5, 4, 3, 1, 2, 0, 2, 1, 2, 3, 3, 2, 1, 2, 2, 2, 4, 2, 4, 0, 7, 5,
       1, 0, 3, 1, 3, 3, 3, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 3, 2, 3,
       2, 3, 2, 2, 2, 1, 3, 1, 2, 2, 0, 1, 1, 4, 4, 6, 0, 3, 3, 1, 2, 3,
       1, 3, 1, 3, 0, 1, 4, 3, 1, 3, 3, 3, 4, 1, 0, 1, 1, 0, 0, 3, 4, 3,
       2, 2, 0, 0, 3, 3, 2, 1, 2, 3, 0, 2, 2, 3, 8, 4, 3, 3, 3, 0, 1, 1,
       4, 1, 1, 3, 2, 1, 0, 1, 3, 3, 2, 4, 0, 2, 3, 1, 1, 1, 1, 0, 5, 3,
       0, 1, 2, 2, 1, 2, 2, 3, 1, 3, 2, 1, 5, 3, 1, 3, 2, 1, 2, 0, 4, 3,
       2, 1, 3, 0, 2, 0, 4, 2, 4, 4, 0, 5, 2, 2, 1, 3, 2, 0, 1, 1, 2, 2,
       2, 2, 0, 1, 0, 2, 0, 3, 2, 3, 1, 0, 3, 0, 2, 4, 0, 1, 1, 1, 2, 1,
       1, 0, 1, 1, 2, 1, 2, 5, 1, 2, 4, 2, 0, 1, 3, 3, 3, 2, 3, 4, 1, 1,
       3, 0, 0, 4, 2, 1, 2, 5, 2, 1, 5, 1, 0, 3, 2, 0, 5, 6, 3, 3, 2, 4,
       2, 2, 2, 0, 2, 4, 1, 1, 5, 1, 2, 2, 4, 0, 1, 2, 2, 1, 1, 3, 3, 3,
       4, 1, 1, 2, 1, 1, 1, 5, 2, 1, 3, 3, 4, 2, 1, 2, 1, 3, 1, 7, 3, 2,
       6, 0, 0, 1, 0, 3, 1, 4, 2, 3, 4, 1, 1, 3, 2,

### UFUNC
They only work on numpy array

In [56]:
# CREATING OWN UFUNC
def addn(x, y):
    return x + y

my_add = np.frompyfunc(addn, 2, 1)   # 2 input args, 1 output arg
my_add([1,2,3], [4,5,6])

array([5, 7, 9], dtype=object)

In [57]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.divide(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.power(arr1, arr2))
print(np.remainder(arr1, arr2)) # mod() can be used as well in place of remainder()
print(np.divmod(arr1, arr2))
print(np.modf(np.divide(arr1, arr2)))  # returns two arrays, one with fractional part and other with integral part of each element of arr1
print(np.absolute(arr1))    # abs() also, in place of absolute()

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[200 231 264 299 336 375]
[ 7766279631452241920  3105570700629903195  5729018530666381312
 -4649523274362944347 -1849127232522420224  1824414961309619599]
[10 11 12 13 14 15]
(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))
(array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ]), array([0., 0., 0., 0., 0., 0.]))
[10 11 12 13 14 15]


### TRUNCATE|FIX - ROUNDING - FLOOR - CEIL

In [58]:
print(np.trunc([-3.1666, 3.6667]))
print(np.fix([-3.1666, 3.6667]))

print(np.around([-3.1666, 3.6667], 2))  # rounding to 2 decimal places. First ignore sign, then round off as positive number, then restore the sign
print(np.floor([-3.1666, 3.6667]))
print(np.ceil([-3.1666, 3.6667]))

[-3.  3.]
[-3.  3.]
[-3.17  3.67]
[-4.  3.]
[-3.  4.]


### Logarithm
By default, only numpy provided log ufuncs are log2, log10, log {e}.
Other base ufunc need to be made from frompyfunc()

In [60]:
print(np.log2(np.arange(1, 10)))
print(np.log10(np.arange(1, 10)))
print(np.log(np.arange(1, 10)))


def log3(x):
    return np.log(x)/np.log(3)

log3_v = np.frompyfunc(log3, 1, 1)
print(log3_v(np.arange(1, 10)))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[np.float64(0.0) np.float64(0.6309297535714574) np.float64(1.0)
 np.float64(1.2618595071429148) np.float64(1.4649735207179269)
 np.float64(1.6309297535714573) np.float64(1.7712437491614221)
 np.float64(1.892789260714372) np.float64(2.0)]


### SUMMATIONS - PRODUCTS - DIFFERENCE

In [72]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(np.add(arr1, arr2))


print(np.sum(arr1))
print(np.sum(arr1, axis=0))   # same as above as arr1 is 1D array
# print(np.sum(arr1, axis=1))   # error as arr1 is 1D array
print(np.sum([arr1, arr2], axis=0))   # sum of each column
print(np.sum([arr1, arr2]))
print(np.sum([arr1, arr2], axis=1))


print(np.cumsum(arr1))
print(np.cumsum([arr1, arr2]))
print(np.cumsum([arr1, arr2], axis=0))
print(np.cumsum([arr1, arr2], axis=1))


print("\n\nPRODUCTS\n")

print(np.prod(arr1))
print(np.prod([arr1, arr2]))
print(np.prod([arr1, arr2], axis=0))
print(np.prod([arr1, arr2], axis=1))

print(np.cumprod(arr1))
print(np.cumprod([arr1, arr2]))
print(np.cumprod([arr1, arr2], axis=0))
print(np.cumprod([arr1, arr2], axis=1))


print("\n\nDIFFERENCE\n")

print(np.diff(arr1))
print(np.diff([arr1, arr2]))
print(np.diff([arr1, arr2], axis=0))
print(np.diff([arr1, arr2], axis=1))


[2 4 6]
6
6
[2 4 6]
12
[6 6]
[1 3 6]
[ 1  3  6  7  9 12]
[[1 2 3]
 [2 4 6]]
[[1 3 6]
 [1 3 6]]


PRODUCTS

6
36
[1 4 9]
[6 6]
[1 2 6]
[ 1  2  6  6 12 36]
[[1 2 3]
 [1 4 9]]
[[1 2 6]
 [1 2 6]]


DIFFERENCE

[1 1]
[[1 1]
 [1 1]]
[[0 0 0]]
[[1 1]
 [1 1]]


### SET OPERATIONS

In [74]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

print(np.unique(arr))

print(np.union1d(arr, [5,6,7,8,9]))   # union of two 1D arrays

arr1 = np.unique(arr)
print(np.intersect1d(arr, [5,6,7,8,9]))
print(np.intersect1d(arr1, [5,6,7,8,9], assume_unique=True))  # faster if both arrays are unique

print(np.setdiff1d(arr, [5,6,7,8,9]))
print(np.setdiff1d(arr1, [5,6,7,8,9], assume_unique=True))  # faster if both arrays are unique

print(np.setxor1d(arr, [5,6,7,8,9]))   # elements in arr1 or arr2 but not in both
print(np.setxor1d(arr1, [5,6,7,8,9], assume_unique=True))   # elements in arr1 or arr2 but not in both

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]
[5 6 7]
[5 6 7]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4 8 9]
[1 2 3 4 8 9]


In [76]:
arr = np.array([1, 3, 7, 2])
np.argmax(arr)      # Output: 2  (since arr[2] == 7 is the max)

arr2 = np.array([[1, 4], [6, 2]])
print(np.argmax(arr2))     # Output: 2 (the flattened index)
print(np.argmax(arr2, axis=0))  # Output: [1 0], max along each column
print(np.argmax(arr2, axis=1))  # Output: [1 0], max along each row

2
[1 0]
[1 0]
