In [1]:
import numpy as np

In [17]:
array = np.arange(1000)
array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [18]:
# Example of fancy indexing- If we want any specific set of index, either from row or column, we pass a list of those row|col numsas an index.
print(array[[1,5,78]])

[ 1  5 78]


In [19]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
np.arange(15).reshape(3, 5)[[0,2], 1::2]

array([[ 1,  3],
       [11, 13]])

In [21]:
np.arange(15).reshape(3, 5)[:-1:2, 1::2]

array([[1, 3]])

In [22]:
np.arange(15).reshape(3, 5)[:-1:2]

array([[0, 1, 2, 3, 4]])

In [23]:
print(array.size * array.itemsize)  # or simply array.nbytes

8000


In [25]:
a=np.array([1, 2, 3])
a.ndim

1

In [26]:
a.dtype

dtype('int64')

In [27]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], ndmin=6)
a.ndim, a.shape, a.size, a

(6,
 (1, 1, 1, 1, 3, 3),
 9,
 array([[[[[[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]]]]]))

In [28]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
a.ndim, a.size, a.itemsize

(2, 9, 8)

In [29]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.float64)
a.dtype, a.itemsize, a.shape, a

(dtype('float64'),
 8,
 (3, 3),
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]))

In [30]:
np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [31]:
np.zeros( (3, 4) )    # if 1d array is there, np.zeros(length of 1 d array)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones( (2, 5) , dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [33]:
# generic
np.full( (2,2), 99 )

array([[99, 99],
       [99, 99]])

In [34]:
np.full_like(a, 78) # returns new array of shape of a, with 78

array([[78., 78., 78.],
       [78., 78., 78.],
       [78., 78., 78.]])

In [35]:
np.full(a.shape, 56)    # a wont get changed

array([[56, 56, 56],
       [56, 56, 56],
       [56, 56, 56]])

In [36]:
np.arange(1,5)

array([1, 2, 3, 4])

In [37]:
np.arange(1,5,2)

array([1, 3])

In [38]:
np.linspace(1, 5, 10)   # linearly spaced 10 numbers between 1 and 5 both included

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [40]:
print(a.reshape(-1, 3))   # -1 means whatever is required to make it 3 columns
# print(a.reshape(-1, 5))  # error as 5 columns not possible with 6 elements

[[1 2 3]
 [4 5 6]]


In [41]:
a = a.ravel()   # to flatten the array. Not fixed to give copy or view of original array
a, a.base

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [42]:
a.flatten() # gives a copy of flattened array

array([1, 2, 3, 4, 5, 6])

In [43]:
a.reshape(-1) # gives a view of flattened array

array([1, 2, 3, 4, 5, 6])

In [44]:
a.flat  # gives flatter iterable object, NOT numpy array

In [45]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
a.min(), a.max(), a.sum(axis=1)

(np.int64(1), np.int64(9), array([ 6, 15, 24]))

In [46]:
b=np.array([[1,1,1], [1,1,1], [1,1,1]]) # matrix product
print(a)
print(b)
np.dot(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [47]:
# stacking two arrays together
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a, b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]] [[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [48]:
a=np.array([np.arange(15), np.arange(15,30)])
print(a)
print(np.hsplit(a,3))   # give only that number which is possible, i.e., output arrays should be of same shape
# similar goes with vsplit. Remember, the dimension of array will NOT gets reduced in both the cases

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [ ]:
np.array_split(np.arange(9), 4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [ ]:
np.array_split(np.arange(9), 10)    # as expected, if it can give array of different size, it can also give array with no elemnts

In [50]:
# np.vsplit(np.arange(15).reshape(3, -1), 2)  # give only that number which is possible, i.e., output arrays should be of same shape

In [51]:
np.array_split(np.arange(15).reshape(-1, 5), 2, axis=1) # axis=0 is default

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14]])]

In [52]:
np.array_split(np.arange(15).reshape(-1, 5), 2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]])]

In [53]:
np.split(np.arange(15).reshape(3, -1), 5, axis=1)  # axis=0 is default which puts vertical splitter. If single integer is passed as number of splits, then it should equally divides the array otherwise ValueError is thrown. If a tuple is passed instead of number of splits, then splitters are placed before that axis on right. If indices exceeds the index of array, then empty array is returned.

[array([[ 0],
        [ 5],
        [10]]),
 array([[ 1],
        [ 6],
        [11]]),
 array([[ 2],
        [ 7],
        [12]]),
 array([[ 3],
        [ 8],
        [13]]),
 array([[ 4],
        [ 9],
        [14]])]

In [54]:
# np array indexing with boolean array
a=np.arange(12).reshape(3,4)
b = a > 4   # boolean array of dimension of 'a'. Another way to get just the indexes of True, is to use arr.where(conditional_expr) which return an array of indexes of elements, each array contains indx of specific 1-dim from n-dimensions, which holds true.
print(b)
print(a[b]) # or directly a[a>4]
a[b]=-1
print(a)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


np.where is used when:
1. we want index of the elements where condition satisfied.
2. we want direct operation on element based on condition, BUT NOT INPLACE, unlike arr[arr%2==1]=-1.
3. direct operation on element based on both of the boolean values.
4. we want a true copy of the original array when direct operation is applied on original array elements copy.

In [55]:
ta = np.arange(15)
np.where(ta%3==1)

(array([ 1,  4,  7, 10, 13]),)

In [56]:
ta = np.arange(15).reshape(3, 5)
np.where(ta%2==1)

(array([0, 0, 1, 1, 1, 2, 2]), array([1, 3, 0, 2, 4, 1, 3]))

In [57]:
np.where(ta%2==1, -2, ta)

array([[ 0, -2,  2, -2,  4],
       [-2,  6, -2,  8, -2],
       [10, -2, 12, -2, 14]])

In [58]:
# there are many other search and sort ways:
np.sort(arr)    # NOT INPLACE SORT. SO, store this value into the original array.

NameError: name 'arr' is not defined

In [59]:
# np.nditer() function - For iterating through each element
a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='C'):   # default w/o order, row major order, C, python
    print(x)

for x in np.nditer(a, order='F'):   # column major order like Fortan, Matlab
    print(x)

for x in np.nditer(a, order='A'): # choose whatever is fastest
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
0
4
8
1
5
9
2
6
10
3
7
11
0
1
2
3
4
5
6
7
8
9
10
11


In [60]:
# printing 1D array instead of 0D array
a = np.arange(12).reshape(3,4)
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [61]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [62]:
b=np.arange(3, 15,4).reshape(3, 1)
print(b)
for x,y in np.nditer([a,b], order='C'): # this will work only if dimensions are equal or if one of the array dimension is 1
    print(x,y)

[[ 3]
 [ 7]
 [11]]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [63]:
for idx, ele in np.ndenumerate(a):  # iterates element wise like nditer, but gives a tuple of index as well.
    print(idx, ele)

(0, 0) 0
(0, 1) 1
(0, 2) 4
(0, 3) 9
(1, 0) 16
(1, 1) 25
(1, 2) 36
(1, 3) 49
(2, 0) 64
(2, 1) 81
(2, 2) 100
(2, 3) 121


In [64]:
# axis param only possible when array is at least 2D or above. Still it is optional. If axis param is not given in any dimensional array, then 1D array is returned where each elemet is repreated n times.
a= np.array([[1,2,3]])
np.repeat(a, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [65]:
a= np.array([[1,2,3], [4,5,6]])
np.repeat(a,3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
np.arange(9).reshape(3,3).repeat(3)

In [66]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
a = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
a[1:-1, 1:-1] = z
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Linear Algebra

In [69]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)  # or, a @ b

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [70]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

https://docs.scipy.org/doc/numpy/reference/routines.math.html

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### Statistics - Some menthods could also be methods of array itself, but I prefer calling them as np static methods instead of calling like arr.stat_func([axis])

In [71]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.min(stats)

np.int64(1)

In [73]:
np.min(stats, axis=0)

array([1, 2, 3])

In [74]:
np.min(stats, axis=1)

array([1, 4])

In [75]:
np.max(stats)

np.int64(6)

In [76]:
np.max(stats, axis=0)   # axis=0 denotes columnwise. So, take one column at a time -> find minimum from that column -> append that element in aswer array -> hop on next column and do the same until all column exhausts. The answer array will be of shape(1, col_count)

array([4, 5, 6])

In [77]:
np.max(stats, axis=1)   # array of shape (1, row_count) contains the max values element form each row

array([3, 6])

In [78]:
np.std(stats)

np.float64(1.707825127659933)

In [79]:
np.std(stats, axis=0)

array([1.5, 1.5, 1.5])

In [80]:
np.var(stats)

np.float64(2.9166666666666665)

In [81]:
np.var(stats, axis=1)

array([0.66666667, 0.66666667])

In [82]:
np.sum(stats)

np.int64(21)

In [83]:
np.sum(stats, axis=1)

array([ 6, 15])

In [84]:
np.mean(stats)

np.float64(3.5)

In [85]:
np.median(stats, axis=0)

array([2.5, 3.5, 4.5])

In [86]:
np.sin(stats)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [87]:
np.exp(stats)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [88]:
np.sqrt(stats)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [89]:
np.percentile(stats, 25)

np.float64(2.25)

In [90]:
np.percentile(stats, (0, 25, 50, 100))

array([1.  , 2.25, 3.5 , 6.  ])

In [91]:
np.percentile(stats, 25, axis=0)

array([1.75, 2.75, 3.75])

In [ ]:
np.percentile(stats, (0, 25, 50, 75, 100), axis=0)

array([[1.    , 2.    , 3.    ],
       [1.0075, 2.0075, 3.0075],
       [1.015 , 2.015 , 3.015 ],
       [1.0225, 2.0225, 3.0225],
       [1.03  , 2.03  , 3.03  ]])

In [94]:
np.conjugate(stats) # good for complex numbers elements where we can find conjugate of them.

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.transpose(stats) # or, stats.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Load data from a file

i - integer;
b - boolean;
u - unsigned integer;
f - float;
c - complex float;
m - timedelta;
M - datetime;
O - object;
S - string;
U - unicode string;
V - fixed chunk of memory for other type ( void );

In [100]:
np.genfromtxt('./sosurveydataset/numdata.csv', delimiter=',').astype('int16')   # OR 'i16'. We can simply give 'int', 'float', 'object', 'str', etc. and it'll pick the default byte-sized version of that data type. Converting from higher byte to lower byte, data is simply lost, not get rounded off

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)

In [101]:
# arr.view() V/S arr.copy() 
# Former BASED ON the original array, later creates a new array without reference to the original array arr as BASE.
# any change to original arr or viewed arr will be reflected in both the arrays. But copy is independent.
# to check if an array is view or copy, use arr.base. If it is None, then it is copy, else view.
# ARR.BASE - Its not a method, its an attribute which returns the base array if the array is a view, else returns None.

## DISTRIBUTIONS

In [ ]:
np.random.rand(4,2)    # uniform dist. [0,1) -  GIVING DIMEMSION IS OPTIONAL

array([[0.24396129, 0.23130017],
       [0.32097552, 0.32065666],
       [0.52768836, 0.87193957],
       [0.97807832, 0.06548629]])

In [ ]:
np.random.uniform(-1, 2, size=(10,2))   # same as above for dimension, Does not anything, but can take any attr mentioned

array([[-0.67463274,  0.085273  ],
       [ 1.56156485, -0.78549758],
       [-0.88435373,  1.08427503],
       [ 1.09879046,  1.30396195],
       [ 1.18837501,  1.96939558],
       [ 0.86860893,  0.80233468],
       [ 1.31180257, -0.24480002],
       [ 1.79552829,  0.52743069],
       [ 0.76804952,  1.57627154],
       [ 1.64704196,  0.69997762]])

In [ ]:
np.random.randn(3,2)   # std normal dist. [0,1) - Dimension is not required

array([[-0.47972926, -0.03331148],
       [-0.50245931,  0.71922631],
       [ 0.61349142,  1.13619523]])

In [ ]:
np.random.normal(loc=0, scale=1, size=(3,2))

array([[-0.36049477,  1.26472894],
       [ 0.47341424, -0.36650912],
       [ 0.08074824,  0.04337246]])

Till here, we could generate the floats. But if we need to generate the integer only, then we use randint, which generates 1 or s sized 

In [ ]:
np.random.randint(1)

0

In [ ]:
a=np.random.randint(100, size=(2, 15))    # literally, instead of size, there should be shape. BUT HERE IT IS SIZE. We can aslo give the lower limit(inclusive) and upper limit(exclusive), and size of any shape
# np.randoom.random_integer() # attrs like randint, where high is inclusive
print(type(a), a)
np.any(a>50, axis=0)

<class 'numpy.ndarray'> [[61 15 39 23 72 50 95 58 95 70 88 72 12 49 24]
 [81  6 87 21 70 32 62 35 44 91 86  9 61 86 17]]


array([ True, False,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False])

In [ ]:
a= np.array([1,2,3])

In [ ]:
np.random.random((3,4))

array([[0.5329453 , 0.75114702, 0.12667169, 0.75187012],
       [0.76358583, 0.26101494, 0.72738739, 0.72579276],
       [0.56196889, 0.7201724 , 0.35485731, 0.9656752 ]])

In [ ]:
np.random.random(a.shape)*10

array([8.42335025, 3.04025602, 9.3396699 ])

In [ ]:
np.random.random_sample(a.shape)*10

array([8.54280632, 9.81332418, 2.68404778])

In [ ]:
((a>20) & (a<60))

array([False, False, False])

In [ ]:
np.random.choice([2,3,4,5,6,7,8], size=(3, 5))

array([[4, 2, 4, 2, 2],
       [8, 3, 6, 5, 5],
       [7, 3, 3, 7, 8]])

In [ ]:
np.random.choice([2,3,4,5], p=[0.1, 0.3, 0.6, 0.0], size=(100,))    # we can specify the probablities of random variable/choices also

array([4, 4, 4, 3, 4, 3, 4, 3, 4, 3, 2, 4, 3, 3, 4, 4, 4, 4, 3, 4, 4, 4,
       4, 3, 4, 4, 4, 4, 4, 3, 3, 2, 3, 3, 3, 4, 3, 3, 4, 4, 4, 3, 4, 3,
       4, 4, 4, 2, 3, 4, 3, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 3, 3, 3, 4,
       3, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4,
       4, 4, 3, 3, 4, 4, 2, 2, 4, 3, 3, 3])

In [ ]:
b = np.array([1, 2, 3, 4, 5])
np.random.shuffle(b)
b   # shuffles the array inplace. In multi-dimension array, all the elements are shuffeled.

array([2, 4, 1, 5, 3])

In [ ]:
# seed makes the random numbers predictable. That is, everytime, for the same code, same random output will be generated.
# np.random.seed()    # seed(int_val)

In [102]:
np.random.normal(loc=1, scale=2, size=(100,200))  # mean, stddev, size

array([[ 0.63241177,  3.04684705,  1.84682272, ..., -1.40659309,
        -0.06964131, -1.68169928],
       [ 2.34970895,  0.59916396,  4.00281523, ..., -3.26656553,
         4.00569043,  1.83649829],
       [ 1.25336602,  2.58522307,  3.98396715, ...,  1.10727734,
         0.38932252,  4.94192755],
       ...,
       [-0.21996686,  3.02047211,  1.9867131 , ..., -0.06373285,
         0.58647779, -0.79837638],
       [ 3.68323747,  0.65052195, -0.75635556, ...,  2.0738028 ,
        -2.55373871, -3.08362507],
       [-1.37554582, -0.66028413, -0.35913975, ..., -0.95278386,
        -2.78285533,  0.71361806]], shape=(100, 200))

In [103]:
np.random.binomial(n=10, p=0.5, size=10)   # n=number of trials, p=probability of each trial, size=number of such experiments

array([5, 5, 6, 6, 7, 5, 3, 3, 7, 5])

In [104]:
np.random.uniform(low=1.0, high=10.0, size=(3,4))   # low(inclusive), high(exclusive), size

array([[7.39996265, 9.69173816, 5.43746167, 1.07783782],
       [7.92943641, 2.28406925, 2.43613378, 7.45448786],
       [5.80928044, 4.41317587, 2.77802367, 2.63165558]])

In [105]:
np.random.poisson(lam=2, size=1000)

array([0, 0, 1, 2, 4, 2, 2, 2, 1, 0, 2, 8, 2, 2, 1, 6, 2, 1, 1, 2, 3, 2,
       1, 4, 3, 1, 1, 3, 4, 2, 1, 5, 3, 4, 1, 2, 1, 2, 1, 4, 3, 2, 1, 0,
       2, 2, 1, 3, 1, 1, 2, 1, 1, 2, 2, 1, 0, 3, 2, 3, 0, 3, 2, 0, 0, 4,
       3, 1, 2, 4, 3, 2, 1, 1, 3, 2, 4, 2, 1, 3, 3, 0, 2, 1, 5, 3, 2, 2,
       4, 3, 2, 1, 2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 0, 0, 5, 2, 2, 2, 2, 2,
       1, 1, 2, 2, 6, 1, 5, 2, 3, 0, 5, 2, 1, 2, 4, 0, 4, 4, 1, 3, 2, 2,
       2, 0, 1, 1, 3, 4, 5, 3, 1, 0, 0, 0, 2, 1, 2, 3, 2, 5, 1, 2, 0, 0,
       1, 0, 1, 1, 2, 2, 1, 1, 2, 0, 1, 3, 2, 4, 3, 3, 2, 4, 1, 2, 2, 0,
       1, 1, 0, 5, 2, 3, 1, 2, 1, 1, 3, 3, 3, 2, 1, 2, 3, 2, 3, 4, 3, 2,
       2, 0, 1, 5, 2, 3, 3, 4, 1, 0, 2, 2, 4, 3, 0, 1, 2, 2, 2, 1, 1, 0,
       2, 2, 6, 2, 5, 3, 2, 3, 2, 2, 6, 1, 5, 3, 2, 4, 1, 2, 2, 1, 3, 3,
       2, 2, 1, 0, 0, 1, 0, 5, 1, 5, 0, 2, 2, 0, 1, 5, 1, 1, 2, 1, 1, 1,
       1, 3, 4, 1, 1, 3, 0, 1, 2, 2, 1, 2, 3, 1, 2, 5, 2, 3, 3, 0, 1, 2,
       2, 4, 3, 2, 0, 3, 3, 2, 6, 3, 3, 1, 2, 4, 3,

### UFUNC
They only work on numpy array

In [106]:
# CREATING OWN UFUNC
def addn(x, y):
    return x + y

my_add = np.frompyfunc(addn, 2, 1)   # 2 input args, 1 output arg
my_add([1,2,3], [4,5,6])

array([5, 7, 9], dtype=object)

In [107]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.divide(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.power(arr1, arr2))
print(np.remainder(arr1, arr2)) # mod() can be used as well in place of remainder()
print(np.divmod(arr1, arr2))
print(np.modf(np.divide(arr1, arr2)))  # returns two arrays, one with fractional part and other with integral part of each element of arr1
print(np.absolute(arr1))    # abs() also, in place of absolute()

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[200 231 264 299 336 375]
[ 7766279631452241920  3105570700629903195  5729018530666381312
 -4649523274362944347 -1849127232522420224  1824414961309619599]
[10 11 12 13 14 15]
(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))
(array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ]), array([0., 0., 0., 0., 0., 0.]))
[10 11 12 13 14 15]


### TRUNCATE|FIX - ROUNDING - FLOOR - CEIL

In [108]:
print(np.trunc([-3.1666, 3.6667]))
print(np.fix([-3.1666, 3.6667]))

print(np.around([-3.1666, 3.6667], 2))  # rounding to 2 decimal places. First ignore sign, then round off as positive number, then restore the sign
print(np.floor([-3.1666, 3.6667]))
print(np.ceil([-3.1666, 3.6667]))

[-3.  3.]
[-3.  3.]
[-3.17  3.67]
[-4.  3.]
[-3.  4.]


### Logarithm
By default, only numpy provided log ufuncs are log2, log10, log {e}.
Other base ufunc need to be made from frompyfunc()

In [109]:
print(np.log2(np.arange(1, 10)))
print(np.log10(np.arange(1, 10)))
print(np.log(np.arange(1, 10)))


def log3(x):
    return np.log(x)/np.log(3)

log3_v = np.frompyfunc(log3, 1, 1)
print(log3_v(np.arange(1, 10)))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[np.float64(0.0) np.float64(0.6309297535714574) np.float64(1.0)
 np.float64(1.2618595071429148) np.float64(1.4649735207179269)
 np.float64(1.6309297535714573) np.float64(1.7712437491614221)
 np.float64(1.892789260714372) np.float64(2.0)]


### SUMMATIONS - PRODUCTS - DIFFERENCE

In [110]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(np.add(arr1, arr2))


print(np.sum(arr1))
print(np.sum(arr1, axis=0))   # same as above as arr1 is 1D array
# print(np.sum(arr1, axis=1))   # error as arr1 is 1D array
print(np.sum([arr1, arr2], axis=0))   # sum of each column
print(np.sum([arr1, arr2]))
print(np.sum([arr1, arr2], axis=1))


print(np.cumsum(arr1))
print(np.cumsum([arr1, arr2]))
print(np.cumsum([arr1, arr2], axis=0))
print(np.cumsum([arr1, arr2], axis=1))


print("\n\nPRODUCTS\n")

print(np.prod(arr1))
print(np.prod([arr1, arr2]))
print(np.prod([arr1, arr2], axis=0))
print(np.prod([arr1, arr2], axis=1))

print(np.cumprod(arr1))
print(np.cumprod([arr1, arr2]))
print(np.cumprod([arr1, arr2], axis=0))
print(np.cumprod([arr1, arr2], axis=1))


print("\n\nDIFFERENCE\n")

print(np.diff(arr1))
print(np.diff([arr1, arr2]))
print(np.diff([arr1, arr2], axis=0))
print(np.diff([arr1, arr2], axis=1))


[2 4 6]
6
6
[2 4 6]
12
[6 6]
[1 3 6]
[ 1  3  6  7  9 12]
[[1 2 3]
 [2 4 6]]
[[1 3 6]
 [1 3 6]]


PRODUCTS

6
36
[1 4 9]
[6 6]
[1 2 6]
[ 1  2  6  6 12 36]
[[1 2 3]
 [1 4 9]]
[[1 2 6]
 [1 2 6]]


DIFFERENCE

[1 1]
[[1 1]
 [1 1]]
[[0 0 0]]
[[1 1]
 [1 1]]


### SET OPERATIONS

In [ ]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

print(np.unique(arr))

print(np.union1d(arr, [5,6,7,8,9]))   # union of two 1D arrays

arr1 = np.unique(arr)
print(np.intersect1d(arr, [5,6,7,8,9]))
print(np.intersect1d(arr1, [5,6,7,8,9], assume_unique=True))  # faster if both arrays are unique. MIGHT THROW Error if any of the array has duplicates

print(np.setdiff1d(arr, [5,6,7,8,9]))
print(np.setdiff1d(arr1, [5,6,7,8,9], assume_unique=True))  # faster if both arrays are unique. MIGHT THROW Error if any of the array has duplicates

print(np.setxor1d(arr, [5,6,7,8,9]))   # elements in arr1 or arr2 but not in both
print(np.setxor1d(arr1, [5,6,7,8,9], assume_unique=True))   # elements in arr1 or arr2 but not in both. MIGHT THROW Error if any of the array has duplicates

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]
[5 6 7]
[5 6 7]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4 8 9]
[1 2 3 4 8 9]


In [112]:
arr = np.array([1, 3, 7, 2])
np.argmax(arr)      # Output: 2  (since arr[2] == 7 is the max)

arr2 = np.array([[1, 4], [6, 2]])
print(np.argmax(arr2))     # Output: 2 (the flattened index)
print(np.argmax(arr2, axis=0))  # Output: [1 0], max along each column
print(np.argmax(arr2, axis=1))  # Output: [1 0], max along each row

2
[1 0]
[1 0]


### Broadcasting functions - Element-wise operations

In [113]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [114]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [115]:
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])

In [116]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2 *= arr1
arr2

In [119]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6, 12).reshape(3,2)

In [120]:
# Now this can be done in 2 ways. Where I generally prefer the first way
# 1.
print(np.dot(arr3, arr4))
# 2.
print(arr3.dot(arr4))

[[ 28  31]
 [100 112]]
[[ 28  31]
 [100 112]]


#### Broadcasting is smooth when 2 arrays are of same shape in arithmetic operations. But when shape is dissimilar, then smaller array is broadcasted to thwe size of larger array so that they have compatible shapes.

In [121]:
np.arange(3)+5

array([5, 6, 7])

In [122]:
np.ones((3,3))+np.arange(3) # Here [0,1,2] will be added to each row of ones

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(3)+np.ones((3,3))

In [123]:
np.arange(3).reshape((3,1))+np.arange(3)    # adding a column vector to row vector, NOT ELEMENTWISE OPERATION. We observe that operation starts to perform in row order. So, taking corresponding row from vec1 and vec2 and then add as [0] from [0,1,2](vertical) + [0,1,2] ==> [0+0, 0+1, 0+2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.arange(3)+np.arange(3).reshape((3,1))    # throw err because for second row of second vector, there is no operand on its left to which it'll get added to.