In [1]:
import numpy as np
import plotly.graph_objects as go

In [ ]:
# Data: 4 points with perfectly correlated features X1, and X2, and outputs y
X = np.array([[1, 2], [2, 4], [3, 6], [4, 8]])  # Perfectly correlated features X1 and X2 (the columns are linearly dependent)
y = np.array([5, 9, 13, 17])

In [3]:
# Add intercept term for Ridge regression
X_with_intercept = np.hstack([np.ones((X.shape[0], 1)), X])

In [ ]:
# Ridge Regression function setup
lambda_ridge = 0.1
I = np.eye(X_with_intercept.shape[1])   # Identity matrix for ridge regularization
beta_ridge = np.linalg.inv(X_with_intercept.T @ X_with_intercept + lambda_ridge * I) @ X_with_intercept.T @ y

In [ ]:
# Create a grid for plotting. We are assuming X2 = 2 * X1 due to perfect correlation between features. In case of fetaures, OLS doesn't work. So we use Ridge regression, where diagonal term is getting added with lambda to prevent invertibility of a matrix.
x1_range = np.linspace(0, 5, 20)
x2_range = 2 * x1_range  # Since X2 = 2 * X1
X1_mesh, X2_mesh = np.meshgrid(x1_range, x2_range)
Y_mesh = beta_ridge[0] + beta_ridge[1] * X1_mesh + beta_ridge[2] * X2_mesh

In [9]:
# Plotting using plotly
fig = go.Figure(data=[go.Scatter3d(x=X[:, 0], y=X[:, 1], z=y, mode='markers', marker=dict(size=5, color='red'), name='Data Points'),
                      go.Surface(x=X1_mesh, y=X2_mesh, z=Y_mesh, opacity=0.5, name='Ridge Regression Plane')])
fig.update_layout(scene=dict(
                    xaxis_title='X1', 
                    yaxis_title='X2',
                    zaxis_title='y'),
                    title='Ridge Regression with Correlated Features in 3D hyperplane')

In [7]:
# Predicted hypothesis values
beta_ridge

array([0.90460099, 0.80582272, 1.61164544])

In [11]:
# Compare prediction with actual answer
beta_0 = 0.90460099
beta_1 = 0.80582272
beta_2 = 1.61164544

# data points
X_1 = np.array([1, 2, 3, 4])
X_2 = 2 * X_1  # Since X2 = 2 * X1

# Calculate predictions
predictions = beta_0 + beta_1 * X_1 + beta_2 * X_2

# Show calculated predictions, Actual values
predictions, y

(array([ 4.93371459,  8.96282819, 12.99194179, 17.02105539]),
 array([ 5,  9, 13, 17]))